---
title: "Title of your report"
author: "fmcv76"
date: "02/04/24"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

## Initial Data Loading and Checks 

```{r include = FALSE}

library(lme4)
library(lmerTest)
library(performance)
library(ggplot2)
library(scales)
library(sjPlot)
library(tidyverse)
library(tinytex)
library(wordcountaddin)

```

```{r}

# Load data 
mst_data_wide = read.csv("https://andygolightly.github.io/teaching/MATH43515/summative/alasdair.csv", 
                    header = TRUE)

# Preprocess long data 
mst_data = mst_data_wide %>% 
  tidyr::pivot_longer(cols = c(Responset1, Responset2, Responset3), 
                      names_to = "Time", 
                      values_to = "Response") %>% # Reshape data to long format 
  dplyr::mutate(Time = case_when(Time == "Responset1" ~ "1", 
                                 Time == "Responset2" ~ "2", 
                                 Time == "Responset3" ~ "3", 
                                 TRUE ~ NA)) %>% 
  dplyr::rename(Treatment = Trt) %>% 
  dplyr::mutate(ID = as.factor(ID), 
                Hospital = as.factor(Hospital), 
                Treatment = as.factor(Treatment), 
                Gender = as.factor(Gender), 
                Size = as.factor(Size), 
                Time = as.factor(Time))

# Preprocess wide data 
mst_data_wide = mst_data_wide %>% 
  dplyr::rename(Treatment = Trt) %>% 
  dplyr::mutate(ID = as.factor(ID), 
                Hospital = as.factor(Hospital), 
                Treatment = as.factor(Treatment), 
                Gender = as.factor(Gender), 
                Size = as.factor(Size))

# Check for NAs
colSums(is.na(mst_data))

```

## Introduction 

__Summary Statistics__

```{r echo = FALSE}

# Summary statistics 
mst_data_wide %>% 
  dplyr::select(-c(ID, Hospital)) %>% 
  summary()

```

```{r}

# Distribution of stress scores at month 1 by intervention group histogram 
ggplot(data = mst_data_wide, aes(x = Responset1, fill = Treatment)) +
  geom_histogram(aes(y = ..count..), binwidth = 1, colour = "black", position = "identity", alpha = 0.3) +
  scale_fill_manual(values = c("1" = "red", "0" = "blue")) +
  scale_x_continuous(breaks = breaks_width(1), minor_breaks = NULL) +
  scale_y_continuous(breaks = breaks_width(2)) +
  labs(x = "Stress Scores", y = "Count", title = "Distribution of Stress Scores Overlaid by Intervention Group - Month 1") +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 0.5), axis.text = element_text(color = "black", size = 12),
        axis.title = element_text(size = 14), plot.title = element_text(size = 14, face = "bold"))

```

```{r}

# Distribution of stress scores at month 2 by intervention group histogram 
ggplot(data = mst_data_wide, aes(x = Responset2, fill = Treatment)) +
  geom_histogram(aes(y = ..count..), binwidth = 1, colour = "black", position = "identity", alpha = 0.3) +
  scale_fill_manual(values = c("1" = "red", "0" = "blue")) +
  scale_x_continuous(breaks = breaks_width(1), minor_breaks = NULL) +
  scale_y_continuous(breaks = breaks_width(2)) +
  labs(x = "Stress Scores", y = "Count", title = "Distribution of Stress Scores Overlaid by Intervention Group - Month 2") +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 0.5), axis.text = element_text(color = "black", size = 12),
        axis.title = element_text(size = 14), plot.title = element_text(size = 14, face = "bold"))

```

```{r}

# Distribution of stress scores at month 3 by intervention group histogram 
ggplot(data = mst_data_wide, aes(x = Responset3, fill = Treatment)) +
  geom_histogram(aes(y = ..count..), binwidth = 1, colour = "black", position = "identity", alpha = 0.3) +
  scale_fill_manual(values = c("1" = "red", "0" = "blue")) +
  scale_x_continuous(breaks = breaks_width(1), minor_breaks = NULL) +
  scale_y_continuous(breaks = breaks_width(2)) +
  labs(x = "Stress Scores", y = "Count", title = "Distribution of Stress Scores Overlaid by Intervention Group - Month 3") +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 0.5), axis.text = element_text(color = "black", size = 12),
        axis.title = element_text(size = 14), plot.title = element_text(size = 14, face = "bold"))

```

## Word Count

```{r warning = FALSE, include = FALSE}

n_words = paste0("Word Count: ", as.character(word_count()))

```

```{r echo = FALSE}

print(n_words)

```
